services:
  portfolio-cms:
    extends:
      file: ./portfolio-cms/docker-compose.dev.yml
      service: portfolio-cms
    networks:
      - portfolio-local

  portfolio-web:
    extends:
      file: ./portfolio-web/docker-compose.dev.yml
      service: portfolio-web
    networks:
      - portfolio-local

  portfolio-db:
    container_name: portfolio-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - portfolio-local

volumes:
  strapi-data:

networks:
  portfolio-local:
    name: portfolio-local
    driver: bridge
