version: '3'

services:
  portfolio-web:
    container_name: portfolio-web
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    pull_policy: build
